/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoamiRouteImport } from './routes/whoami'
import { Route as IndexRouteImport } from './routes/index'

const WhoamiRoute = WhoamiRouteImport.update({
  id: '/whoami',
  path: '/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/whoami': typeof WhoamiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/whoami': typeof WhoamiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/whoami': typeof WhoamiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/whoami'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/whoami'
  id: '__root__' | '/' | '/whoami'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhoamiRoute: typeof WhoamiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whoami': {
      id: '/whoami'
      path: '/whoami'
      fullPath: '/whoami'
      preLoaderRoute: typeof WhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhoamiRoute: WhoamiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
