/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv src/worker-configuration.d.ts` (hash: 011c4ea1cf4c2d50fd99c24117f395f0)
interface __BaseEnv_CloudflareEnv {
  CF_VERSION_METADATA: WorkerVersionMetadata;
  DEPLOYED_AT: string;
  DEPLOY_RUN_ID: string;
  DEPLOY_SHA: string;
  INSTANCE_ID: string;
  SENTRY_DSN: string;
  SENTRY_ENVIRONMENT: string;
  SENTRY_RELEASE: string;
  SENTRY_SERVICE: string;
  TURNSTILE_SITE_KEY: string;
  PREVIEW_SMOKE_SESSION_CREDENTIALS?: string;
  WORKOS_CLIENT_ID: string;
  WORKOS_AUTHKIT_ORIGIN: string;
  API: Fetcher /* insecur-api-preview */ | Fetcher /* insecur-api */;
  RUNTIME:
    | Service /* entrypoint RuntimeService from insecur-runtime-preview */
    | Service /* entrypoint RuntimeService from insecur-runtime */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface PreviewEnv {
    CF_VERSION_METADATA: WorkerVersionMetadata;
    DEPLOYED_AT: string;
    DEPLOY_RUN_ID: string;
    DEPLOY_SHA: string;
    INSTANCE_ID: string;
    SENTRY_DSN: string;
    SENTRY_ENVIRONMENT: string;
    SENTRY_RELEASE: string;
    SENTRY_SERVICE: string;
    TURNSTILE_SITE_KEY: string;
    PREVIEW_SMOKE_SESSION_CREDENTIALS: string;
    WORKOS_CLIENT_ID: string;
    WORKOS_AUTHKIT_ORIGIN: string;
    API: Fetcher /* insecur-api-preview */;
    RUNTIME: Service /* entrypoint RuntimeService from insecur-runtime-preview */;
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "DEPLOYED_AT"
      | "DEPLOY_RUN_ID"
      | "DEPLOY_SHA"
      | "INSTANCE_ID"
      | "SENTRY_DSN"
      | "SENTRY_ENVIRONMENT"
      | "SENTRY_RELEASE"
      | "SENTRY_SERVICE"
      | "TURNSTILE_SITE_KEY"
      | "PREVIEW_SMOKE_SESSION_CREDENTIALS"
      | "WORKOS_CLIENT_ID"
      | "WORKOS_AUTHKIT_ORIGIN"
    >
  > {}
}
