/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv src/worker-configuration.d.ts` (hash: 86b74648cda8166a55b51cd0577966c2)
interface __BaseEnv_CloudflareEnv {
  CF_VERSION_METADATA: WorkerVersionMetadata;
  AUDIT_EXPORT_SIGNING_PUBLIC_KEY: string;
  DEPLOYED_AT: string;
  DEPLOY_RUN_ID: string;
  DEPLOY_SHA: string;
  SENTRY_DSN: string;
  SENTRY_ENVIRONMENT: string;
  SENTRY_RELEASE: string;
  SENTRY_SERVICE: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface PreviewEnv {
    CF_VERSION_METADATA: WorkerVersionMetadata;
    AUDIT_EXPORT_SIGNING_PUBLIC_KEY: string;
    DEPLOYED_AT: string;
    DEPLOY_RUN_ID: string;
    DEPLOY_SHA: string;
    SENTRY_DSN: string;
    SENTRY_ENVIRONMENT: string;
    SENTRY_RELEASE: string;
    SENTRY_SERVICE: string;
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "AUDIT_EXPORT_SIGNING_PUBLIC_KEY"
      | "DEPLOYED_AT"
      | "DEPLOY_RUN_ID"
      | "DEPLOY_SHA"
      | "SENTRY_DSN"
      | "SENTRY_ENVIRONMENT"
      | "SENTRY_RELEASE"
      | "SENTRY_SERVICE"
    >
  > {}
}
