import {
  AUDIT_ERROR_CODES,
  AUTH_ERROR_CODES,
  BOOTSTRAP_ERROR_CODES,
  CRYPTO_ERROR_CODES,
  ENVIRONMENT_ERROR_CODES,
  INJECTION_ERROR_CODES,
  ONBOARDING_ERROR_CODES,
  OPERATION_ERROR_CODES,
  SECRET_ERROR_CODES,
  STORE_ERROR_CODES,
  VALIDATION_ERROR_CODES,
  type KnownErrorCode,
} from "@insecur/domain";

/** Enforcing HTTP projection of docs/cli-and-sync.md Error Code To Exit Code Mapping. */
export const HTTP_STATUS_BY_CODE = new Map<KnownErrorCode, number>([
  [AUTH_ERROR_CODES.required, 401],
  [AUTH_ERROR_CODES.expired, 401],
  [AUTH_ERROR_CODES.invalid, 401],
  [AUTH_ERROR_CODES.reauthRequired, 401],
  [AUTH_ERROR_CODES.mfaEnrollmentRequired, 401],
  [AUTH_ERROR_CODES.highAssuranceRequired, 401],
  [AUTH_ERROR_CODES.insufficientScope, 403],
  [VALIDATION_ERROR_CODES.invalidOpaqueResourceId, 400],
  [VALIDATION_ERROR_CODES.invalidVariableKey, 400],
  [VALIDATION_ERROR_CODES.invalidDisplayName, 400],
  [VALIDATION_ERROR_CODES.displayNameEmpty, 400],
  [SECRET_ERROR_CODES.invalidEncoding, 400],
  [SECRET_ERROR_CODES.invalidInputMode, 400],
  [SECRET_ERROR_CODES.emptyValue, 400],
  [SECRET_ERROR_CODES.inputRequired, 400],
  [SECRET_ERROR_CODES.valueTooLarge, 400],
  [SECRET_ERROR_CODES.coordinateInvalid, 404],
  [ENVIRONMENT_ERROR_CODES.invalidLifecycleStage, 400],
  [ENVIRONMENT_ERROR_CODES.protectedEnvironment, 403],
  [ENVIRONMENT_ERROR_CODES.lifecycleImmutable, 400],
  [ENVIRONMENT_ERROR_CODES.previewOptDownRequired, 400],
  [ENVIRONMENT_ERROR_CODES.previewOptDownInvalid, 400],
  [ENVIRONMENT_ERROR_CODES.notFound, 404],
  [ONBOARDING_ERROR_CODES.alreadyProvisioned, 409],
  [ONBOARDING_ERROR_CODES.resourceConflict, 409],
  [ONBOARDING_ERROR_CODES.notInstanceOperator, 403],
  [ONBOARDING_ERROR_CODES.invitationInvalid, 400],
  [ONBOARDING_ERROR_CODES.invitationNotPending, 409],
  [ONBOARDING_ERROR_CODES.invitationInviteeMismatch, 403],
  [ONBOARDING_ERROR_CODES.membershipAlreadyExists, 409],
  [BOOTSTRAP_ERROR_CODES.alreadyBootstrapped, 409],
  [BOOTSTRAP_ERROR_CODES.notBootstrapped, 404],
  [BOOTSTRAP_ERROR_CODES.claimNotAvailable, 404],
  [BOOTSTRAP_ERROR_CODES.alreadyClaimed, 409],
  [BOOTSTRAP_ERROR_CODES.invalidSecret, 401],
  [BOOTSTRAP_ERROR_CODES.authenticatedActorRequired, 401],
  [STORE_ERROR_CODES.runtimeConfigMissing, 503],
  [CRYPTO_ERROR_CODES.decryptFailed, 500],
  [CRYPTO_ERROR_CODES.rootKeyNotConfigured, 503],
  [CRYPTO_ERROR_CODES.tenantDataKeyNotReady, 503],
  [CRYPTO_ERROR_CODES.invalidAadField, 400],
  [AUDIT_ERROR_CODES.eventInvalid, 400],
  [INJECTION_ERROR_CODES.grantDenied, 404],
  [INJECTION_ERROR_CODES.grantExpired, 404],
  [OPERATION_ERROR_CODES.notFound, 404],
  [OPERATION_ERROR_CODES.idempotencyMismatch, 409],
  [OPERATION_ERROR_CODES.invalidIntent, 400],
  [OPERATION_ERROR_CODES.invalidMetadata, 400],
  [OPERATION_ERROR_CODES.staleTransition, 409],
  [OPERATION_ERROR_CODES.invalidTransition, 400],
  [OPERATION_ERROR_CODES.terminalState, 409],
  [OPERATION_ERROR_CODES.notCancelable, 409],
  [OPERATION_ERROR_CODES.notRetryable, 409],
  [OPERATION_ERROR_CODES.staleFencingToken, 409],
  [OPERATION_ERROR_CODES.leaseNotHeld, 409],
  [OPERATION_ERROR_CODES.leaseRequired, 400],
]);
