import {
  APP_CONNECTION_ERROR_CODES,
  AUDIT_ERROR_CODES,
  ABUSE_ERROR_CODES,
  AUTH_ERROR_CODES,
  BOOTSTRAP_ERROR_CODES,
  CRYPTO_ERROR_CODES,
  ENVIRONMENT_ERROR_CODES,
  HIGH_ASSURANCE_ERROR_CODES,
  INJECTION_ERROR_CODES,
  PROVIDER_APP_REGISTRATION_ERROR_CODES,
  RUNTIME_POLICY_ERROR_CODES,
  ONBOARDING_ERROR_CODES,
  OPERATION_ERROR_CODES,
  NOTIFICATION_ERROR_CODES,
  PROTECTED_CHANGE_ERROR_CODES,
  APPROVAL_ERROR_CODES,
  SECRET_ERROR_CODES,
  STORE_ERROR_CODES,
  STORAGE_GATE_ERROR_CODES,
  VALIDATION_ERROR_CODES,
  type KnownErrorCode,
} from "@insecur/domain";

/** Enforcing HTTP projection of docs/cli-and-sync.md Error Code To Exit Code Mapping. */
export const HTTP_STATUS_BY_CODE = new Map<KnownErrorCode, number>([
  [AUTH_ERROR_CODES.required, 401],
  [AUTH_ERROR_CODES.configInvalid, 503],
  [AUTH_ERROR_CODES.expired, 401],
  [AUTH_ERROR_CODES.invalid, 401],
  [AUTH_ERROR_CODES.reauthRequired, 401],
  [AUTH_ERROR_CODES.mfaEnrollmentRequired, 401],
  [AUTH_ERROR_CODES.highAssuranceRequired, 401],
  [AUTH_ERROR_CODES.insufficientScope, 403],
  [AUTH_ERROR_CODES.oidcWrongAudience, 403],
  [AUTH_ERROR_CODES.oidcWrongRepository, 403],
  [AUTH_ERROR_CODES.oidcWrongEnvironment, 403],
  [AUTH_ERROR_CODES.oidcUntrustedSource, 401],
  [AUTH_ERROR_CODES.deployKeyInvalid, 401],
  [AUTH_ERROR_CODES.deployKeyDisabled, 403],
  [AUTH_ERROR_CODES.deployKeyWrongEnvironment, 403],
  [AUTH_ERROR_CODES.deployKeyOverbroadScope, 403],
  [VALIDATION_ERROR_CODES.invalidOpaqueResourceId, 400],
  [VALIDATION_ERROR_CODES.invalidCommandInput, 400],
  [VALIDATION_ERROR_CODES.invalidVariableKey, 400],
  [VALIDATION_ERROR_CODES.invalidDisplayName, 400],
  [VALIDATION_ERROR_CODES.displayNameEmpty, 400],
  [VALIDATION_ERROR_CODES.invalidFeedbackKind, 400],
  [VALIDATION_ERROR_CODES.invalidFeedbackNoteCode, 400],
  [VALIDATION_ERROR_CODES.feedbackAssociationRequired, 400],
  [VALIDATION_ERROR_CODES.feedbackAssociationNotFound, 404],
  [SECRET_ERROR_CODES.invalidEncoding, 400],
  [SECRET_ERROR_CODES.invalidInputMode, 400],
  [SECRET_ERROR_CODES.emptyValue, 400],
  [SECRET_ERROR_CODES.inputRequired, 400],
  [SECRET_ERROR_CODES.valueTooLarge, 400],
  [SECRET_ERROR_CODES.coordinateInvalid, 404],
  [ENVIRONMENT_ERROR_CODES.invalidLifecycleStage, 400],
  [ENVIRONMENT_ERROR_CODES.protectedEnvironment, 403],
  [ENVIRONMENT_ERROR_CODES.nonProtectedEnvironment, 403],
  [ENVIRONMENT_ERROR_CODES.lifecycleImmutable, 400],
  [ENVIRONMENT_ERROR_CODES.previewOptDownInvalid, 400],
  [ENVIRONMENT_ERROR_CODES.notFound, 404],
  [ONBOARDING_ERROR_CODES.alreadyProvisioned, 409],
  [ONBOARDING_ERROR_CODES.resourceConflict, 409],
  [ONBOARDING_ERROR_CODES.notInstanceOperator, 403],
  [ONBOARDING_ERROR_CODES.invitationInvalid, 400],
  [ONBOARDING_ERROR_CODES.invitationNotPending, 409],
  [ONBOARDING_ERROR_CODES.invitationInviteeMismatch, 403],
  [ONBOARDING_ERROR_CODES.membershipAlreadyExists, 409],
  [BOOTSTRAP_ERROR_CODES.alreadyBootstrapped, 409],
  [BOOTSTRAP_ERROR_CODES.notBootstrapped, 404],
  [BOOTSTRAP_ERROR_CODES.claimNotAvailable, 404],
  [BOOTSTRAP_ERROR_CODES.alreadyClaimed, 409],
  [BOOTSTRAP_ERROR_CODES.invalidSecret, 401],
  [BOOTSTRAP_ERROR_CODES.authenticatedActorRequired, 401],
  [STORE_ERROR_CODES.runtimeConfigMissing, 503],
  [STORAGE_GATE_ERROR_CODES.gateBlocked, 503],
  [STORAGE_GATE_ERROR_CODES.gateUnknown, 503],
  [CRYPTO_ERROR_CODES.decryptFailed, 500],
  [CRYPTO_ERROR_CODES.rootKeyNotConfigured, 503],
  [CRYPTO_ERROR_CODES.tenantDataKeyNotReady, 503],
  [CRYPTO_ERROR_CODES.invalidAadField, 400],
  [AUDIT_ERROR_CODES.eventInvalid, 400],
  [HIGH_ASSURANCE_ERROR_CODES.evidenceMissing, 401],
  [HIGH_ASSURANCE_ERROR_CODES.evidenceExpired, 401],
  [HIGH_ASSURANCE_ERROR_CODES.operationMismatch, 404],
  [HIGH_ASSURANCE_ERROR_CODES.actorMismatch, 403],
  [HIGH_ASSURANCE_ERROR_CODES.alreadyConsumed, 401],
  [HIGH_ASSURANCE_ERROR_CODES.clearingDenied, 403],
  [HIGH_ASSURANCE_ERROR_CODES.sessionAssuranceFailed, 401],
  [HIGH_ASSURANCE_ERROR_CODES.invalidRiskReason, 400],
  [ABUSE_ERROR_CODES.rateLimited, 429],
  [INJECTION_ERROR_CODES.grantDenied, 404],
  [INJECTION_ERROR_CODES.grantExpired, 404],
  [RUNTIME_POLICY_ERROR_CODES.notFound, 404],
  [RUNTIME_POLICY_ERROR_CODES.displayNameInUse, 409],
  [RUNTIME_POLICY_ERROR_CODES.invalidBindings, 400],
  [RUNTIME_POLICY_ERROR_CODES.patternBindingRejected, 400],
  [RUNTIME_POLICY_ERROR_CODES.versionImmutable, 409],
  [RUNTIME_POLICY_ERROR_CODES.protectedUseBlocked, 403],
  [RUNTIME_POLICY_ERROR_CODES.disabled, 403],
  [OPERATION_ERROR_CODES.notFound, 404],
  [OPERATION_ERROR_CODES.idempotencyMismatch, 409],
  [OPERATION_ERROR_CODES.invalidIntent, 400],
  [OPERATION_ERROR_CODES.invalidMetadata, 400],
  [OPERATION_ERROR_CODES.staleTransition, 409],
  [OPERATION_ERROR_CODES.invalidTransition, 400],
  [OPERATION_ERROR_CODES.terminalState, 409],
  [OPERATION_ERROR_CODES.notCancelable, 409],
  [OPERATION_ERROR_CODES.notRetryable, 409],
  [OPERATION_ERROR_CODES.staleFencingToken, 409],
  [OPERATION_ERROR_CODES.leaseNotHeld, 409],
  [OPERATION_ERROR_CODES.leaseRequired, 400],
  [PROTECTED_CHANGE_ERROR_CODES.notFound, 404],
  [PROTECTED_CHANGE_ERROR_CODES.invalidTransition, 400],
  [PROTECTED_CHANGE_ERROR_CODES.terminalState, 409],
  [PROTECTED_CHANGE_ERROR_CODES.activeChangeExists, 409],
  [PROTECTED_CHANGE_ERROR_CODES.missingEvidence, 400],
  [PROTECTED_CHANGE_ERROR_CODES.requesterMismatch, 403],
  [PROTECTED_CHANGE_ERROR_CODES.nonProtectedEnvironment, 403],
  [APPROVAL_ERROR_CODES.requestNotFound, 404],
  [APPROVAL_ERROR_CODES.requestNotPending, 409],
  [APPROVAL_ERROR_CODES.invalidDraftSelection, 400],
  [APPROVAL_ERROR_CODES.wildcardSelectionRejected, 400],
  [APPROVAL_ERROR_CODES.promotionChangeSetImmutable, 409],
  [APPROVAL_ERROR_CODES.rollbackTargetNotEligible, 400],
  [APP_CONNECTION_ERROR_CODES.notFound, 404],
  [APP_CONNECTION_ERROR_CODES.resourceConflict, 409],
  [APP_CONNECTION_ERROR_CODES.invalidConnectionMethod, 400],
  [NOTIFICATION_ERROR_CODES.invalidEventCode, 400],
  [NOTIFICATION_ERROR_CODES.subscriptionNotFound, 404],
  [NOTIFICATION_ERROR_CODES.deliveryFailed, 500],
  [NOTIFICATION_ERROR_CODES.signingSecretMissing, 500],
  [PROVIDER_APP_REGISTRATION_ERROR_CODES.notFound, 404],
  [PROVIDER_APP_REGISTRATION_ERROR_CODES.alreadyExists, 409],
]);
