/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv src/worker-configuration.d.ts` (hash: 378752f7e0874dc3d3612d23faffcbab)
interface __BaseEnv_CloudflareEnv {
  BACKUPS: R2Bucket;
  DB: Hyperdrive;
  INSTANCE_ROOT_KEY_V1: SecretsStoreSecret;
  AUDIT_EXPORT_HMAC_KEY_V1: SecretsStoreSecret;
  AUDIT_EXPORT_SIGNING_KEY_V1: SecretsStoreSecret;
  CF_VERSION_METADATA: WorkerVersionMetadata;
  INSTANCE_ID: string;
  SENTRY_DSN: string;
  SENTRY_ENVIRONMENT: string;
  SENTRY_RELEASE: string;
  SENTRY_SERVICE: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface PreviewEnv {
    BACKUPS: R2Bucket;
    DB: Hyperdrive;
    INSTANCE_ROOT_KEY_V1: SecretsStoreSecret;
    AUDIT_EXPORT_HMAC_KEY_V1: SecretsStoreSecret;
    AUDIT_EXPORT_SIGNING_KEY_V1: SecretsStoreSecret;
    CF_VERSION_METADATA: WorkerVersionMetadata;
    INSTANCE_ID: string;
    SENTRY_DSN: string;
    SENTRY_ENVIRONMENT: string;
    SENTRY_RELEASE: string;
    SENTRY_SERVICE: string;
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      "INSTANCE_ID" | "SENTRY_DSN" | "SENTRY_ENVIRONMENT" | "SENTRY_RELEASE" | "SENTRY_SERVICE"
    >
  > {}
}
