import type {
  DisplayName,
  EnvironmentId,
  InjectionGrantId,
  InvitationId,
  KnownErrorCode,
  MembershipId,
  OperationId,
  OrganizationId,
  ProjectId,
  RequestId,
  SecretId,
  SecretVersionId,
  UserId,
  VariableKey,
} from "@insecur/domain";
import type {
  OperatorOrganizationResourceIds,
  ProvisionGuidedOrganizationResourceIds,
} from "@insecur/onboarding";
import type { InjectionGrantIssueSelector } from "@insecur/runtime-injection-issue";
import type { PostAuthRpcInputBase } from "./runtime-rpc-shared.js";

export type { RuntimeRpc } from "./runtime-rpc-interface.js";

/**
 * The RPC contract between the public API Worker and the private Runtime Worker (ADR-0077).
 * Everything here is structured-clone safe: Cloudflare RPC serializes args and returns, so no
 * class instances, methods, or `PlaintextHandle` may cross this seam. The plaintext secret value
 * is encoded to base64url inside the Runtime (see `encodedValueUtf8`) before it crosses back.
 *
 * RPC does NOT propagate custom error properties (only `name`/`message` survive), so the methods
 * return a discriminated result instead of throwing: the API re-throws a structurally-typed error
 * the worker-kit error responder reads. This keeps `code`/`retryable` honest across the binding.
 */

/** Metadata-only secret write outcome (no secret value), mirrors WriteNonProtectedSecretResult. */
export interface RuntimeSecretWritePayload {
  secretId: SecretId;
  secretVersionId: SecretVersionId;
  variableKey: VariableKey;
  createdSecretShape: boolean;
  auditEventId?: string;
}

/** A failure crossing the RPC seam; the API re-throws a `{ code, retryable }`-shaped error. */
export interface RuntimeRpcError {
  readonly code: KnownErrorCode;
  readonly message: string;
  readonly retryable: boolean;
  readonly operationId?: OperationId;
}

export type RuntimeRpcResult<TPayload> =
  | { readonly ok: true; readonly value: TPayload }
  | { readonly ok: false; readonly error: RuntimeRpcError };

export interface ConsumeGrantAllRpcInput {
  readonly organizationId: OrganizationId;
  readonly grantId: InjectionGrantId;
  /** Scoped, audience-bound hop token authenticating the forwarded actor (ADR-0077). */
  readonly actorToken: string;
  /** API-minted request id, threaded into the Runtime audit row and the delivery envelope meta. */
  readonly requestId: RequestId;
}

export interface ConsumeGrantRpcInput {
  readonly organizationId: OrganizationId;
  readonly grantId: InjectionGrantId;
  readonly variableKey?: VariableKey;
  readonly secretId?: SecretId;
  /** Scoped, audience-bound hop token authenticating the forwarded actor (ADR-0077). */
  readonly actorToken: string;
  /** API-minted request id, threaded into the Runtime audit row and the delivery envelope meta. */
  readonly requestId: RequestId;
}

export interface RuntimeGeneratedSecretInput {
  readonly mode: "random";
  readonly lengthBytes: number;
}

interface WriteSecretRpcInputBase {
  readonly organizationId: OrganizationId;
  readonly projectId: ProjectId;
  readonly environmentId: EnvironmentId;
  readonly variableKey: VariableKey;
  readonly secretId?: SecretId;
  readonly allowEmpty?: boolean;
  readonly actorToken: string;
  /** API-minted request id, threaded into the Runtime audit row for the write. */
  readonly requestId: RequestId;
}

export type WriteSecretRpcInput = WriteSecretRpcInputBase &
  (
    | {
        /** UTF-8 secret bytes; structured-clone safe across the binding, never logged. */
        readonly valueUtf8: Uint8Array;
        readonly generate?: never;
      }
    | {
        /** Runtime-local generation request; generated bytes never cross to the public API Worker. */
        readonly generate: RuntimeGeneratedSecretInput;
        readonly valueUtf8?: never;
      }
  );

// --- Non-keyring DB operations forwarded over the seam (ADR-0077) ---
//
// The public API Worker holds no Hyperdrive binding and does zero DB I/O. Every non-keyring DB
// operation runs in the Runtime deploy (the sole holder of `DB`) and is reached over this contract.
// Two trust shapes:
//   - PRE-AUTH calls carry NO actorToken because they run before an authenticated actor exists
//     (admission resolution is the step that maps a WorkOS subject to an insecur `userId`). They are
//     trusted by the private Service Binding boundary itself: the Runtime serves zero public routes,
//     they touch no keyring, and they return only identity/metadata.
//   - POST-AUTH calls carry an `actorToken` (the same scoped hop token write/consume use). The
//     Runtime verifies it and rebuilds the actor; the API never sends an actor object across.

/** PRE-AUTH: resolve a WorkOS subject to its admitted insecur user id (null = not admitted). */
export interface ResolveAdmissionRpcInput {
  readonly instanceId: string;
  readonly workosUserId: string;
}
export interface ResolveAdmissionRpcPayload {
  readonly userId: UserId | null;
}

/** PRE-AUTH: best-effort metadata-only denied-admission audit. */
export interface RecordAdmissionDeniedRpcInput {
  readonly instanceId: string;
  readonly workosUserId: string;
  readonly requestId: RequestId;
}
export interface RecordAdmissionDeniedRpcPayload {
  readonly recorded: true;
}

/** PRE-AUTH: best-effort metadata-only denied audit for public-edge abuse controls. */
export interface RecordAbuseDeniedRpcInput {
  readonly instanceId: string;
  readonly requestId: RequestId;
  readonly eventCode: string;
  readonly reasonCode: KnownErrorCode;
  readonly actorUserId?: UserId | null;
}
export interface RecordAbuseDeniedRpcPayload {
  readonly recorded: true;
}

/** PRE-AUTH: public instance bootstrap phase (the `/status` route is unauthenticated). */
export interface GetBootstrapStatusRpcInput {
  readonly instanceId: string;
}

export interface ProvisionGuidedOrganizationRpcInput extends PostAuthRpcInputBase {
  readonly instanceId: string;
  readonly organizationDisplayName?: DisplayName;
  readonly projectDisplayName?: DisplayName;
  readonly teamDisplayName?: DisplayName;
  readonly environmentDisplayName?: DisplayName;
  readonly resourceIds?: ProvisionGuidedOrganizationResourceIds;
}

export interface CreateOperatorOrganizationRpcInput extends PostAuthRpcInputBase {
  readonly instanceId: string;
  readonly organizationDisplayName?: DisplayName;
  readonly teamDisplayName?: DisplayName;
  readonly resourceIds?: OperatorOrganizationResourceIds;
}

export interface CreateInvitationRpcInput extends PostAuthRpcInputBase {
  readonly organizationId: OrganizationId;
  readonly inviteeUserId: UserId;
  readonly rolePreset: string;
  readonly projectId?: ProjectId;
  readonly invitationId?: InvitationId;
  readonly membershipId?: MembershipId;
}

export interface AcceptInvitationRpcInput extends PostAuthRpcInputBase {
  readonly organizationId: OrganizationId;
  readonly invitationId: InvitationId;
  readonly membershipId?: MembershipId;
}

export interface GetOperationRpcInput extends PostAuthRpcInputBase {
  readonly organizationId: OrganizationId;
  readonly operationId: OperationId;
}

export interface CancelOperationRpcInput extends PostAuthRpcInputBase {
  readonly organizationId: OrganizationId;
  readonly operationId: OperationId;
}

/** Metadata-only cancel outcome for the public API seam. */
export interface CancelOperationRpcPayload {
  readonly operationId: OperationId;
  readonly organizationId: OrganizationId;
  readonly state: string;
  readonly intentCode: string;
  readonly progress: Record<string, unknown>;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly auditEventId: string;
}

export interface IssueInjectionGrantRpcInput extends PostAuthRpcInputBase {
  readonly organizationId: OrganizationId;
  readonly projectId: ProjectId;
  readonly environmentId: EnvironmentId;
  readonly selector: InjectionGrantIssueSelector;
}

export interface CompleteBootstrapClaimRpcInput extends PostAuthRpcInputBase {
  readonly instanceId: string;
  readonly bootstrapSecret: string;
  readonly operatorGrantId: string;
  readonly ownerMembershipId: MembershipId;
}
