/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv src/worker-configuration.d.ts` (hash: 70b28def59815b96d6a7759732207e19)
interface __BaseEnv_CloudflareEnv {
  API_ANALYTICS: AnalyticsEngineDataset;
  ONBOARDING_IP: RateLimit;
  ONBOARDING_ACTOR: RateLimit;
  BOOTSTRAP_IP: RateLimit;
  BOOTSTRAP_ACTOR: RateLimit;
  AUTH_EXCHANGE_IP: RateLimit;
  AUTH_DEVICE_TOKEN_IP: RateLimit;
  CF_VERSION_METADATA: WorkerVersionMetadata;
  DEPLOYED_AT: string;
  DEPLOY_RUN_ID: string;
  DEPLOY_SHA: string;
  INSTANCE_ID: string;
  SENTRY_DSN: string;
  SENTRY_ENVIRONMENT: string;
  SENTRY_RELEASE: string;
  SENTRY_SERVICE: string;
  SENTRY_TRACES_SAMPLE_RATE: string;
  WORKOS_CLIENT_ID: string;
  RUNTIME:
    | Service /* entrypoint RuntimeService from insecur-runtime-preview */
    | Service /* entrypoint RuntimeService from insecur-runtime */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface PreviewEnv {
    API_ANALYTICS: AnalyticsEngineDataset;
    ONBOARDING_IP: RateLimit;
    ONBOARDING_ACTOR: RateLimit;
    BOOTSTRAP_IP: RateLimit;
    BOOTSTRAP_ACTOR: RateLimit;
    AUTH_EXCHANGE_IP: RateLimit;
    AUTH_DEVICE_TOKEN_IP: RateLimit;
    CF_VERSION_METADATA: WorkerVersionMetadata;
    DEPLOYED_AT: string;
    DEPLOY_RUN_ID: string;
    DEPLOY_SHA: string;
    INSTANCE_ID: string;
    SENTRY_DSN: string;
    SENTRY_ENVIRONMENT: string;
    SENTRY_RELEASE: string;
    SENTRY_SERVICE: string;
    SENTRY_TRACES_SAMPLE_RATE: string;
    WORKOS_CLIENT_ID: string;
    RUNTIME: Service /* entrypoint RuntimeService from insecur-runtime-preview */;
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "DEPLOYED_AT"
      | "DEPLOY_RUN_ID"
      | "DEPLOY_SHA"
      | "INSTANCE_ID"
      | "SENTRY_DSN"
      | "SENTRY_ENVIRONMENT"
      | "SENTRY_RELEASE"
      | "SENTRY_SERVICE"
      | "SENTRY_TRACES_SAMPLE_RATE"
      | "WORKOS_CLIENT_ID"
    >
  > {}
}
