/**
 * Plaintext Metadata Allowlist registry (ADR-0070).
 * Every column of every user table must appear here with an explicit category.
 */
import { PLAINTEXT_METADATA_ALLOWLIST_AGENT_SESSIONS } from "./plaintext-metadata-allowlist-agent-sessions.js";
import { PLAINTEXT_METADATA_ALLOWLIST_APP_CONNECTIONS } from "./plaintext-metadata-allowlist-app-connections.js";
import { PLAINTEXT_METADATA_ALLOWLIST_INSTANCE_BOOTSTRAP } from "./plaintext-metadata-allowlist-instance-bootstrap.js";
import { PLAINTEXT_METADATA_ALLOWLIST_RUNTIME_INJECTION } from "./plaintext-metadata-allowlist-runtime-injection.js";
import { PLAINTEXT_METADATA_ALLOWLIST_SECRETS } from "./plaintext-metadata-allowlist-secrets.js";
import { PLAINTEXT_METADATA_ALLOWLIST_PROTECTED_CHANGES } from "./plaintext-metadata-allowlist-protected-changes.js";
import { PLAINTEXT_METADATA_ALLOWLIST_APPROVALS } from "./plaintext-metadata-allowlist-approvals.js";
import { PLAINTEXT_METADATA_ALLOWLIST_WEBHOOKS } from "./plaintext-metadata-allowlist-webhooks.js";

export const PLAINTEXT_METADATA_CATEGORIES = [
  "opaque-id",
  "display-name",
  "type-code",
  "status-code",
  "timestamp",
  "actor-id",
  "count",
  "flag",
  "ciphertext-ref",
  "key-version",
  "validated-payload",
  "plaintext-lookup-key",
  "verifier-material",
] as const;

export type PlaintextMetadataCategory = (typeof PLAINTEXT_METADATA_CATEGORIES)[number];

export interface PlaintextMetadataAllowlistEntry {
  category: PlaintextMetadataCategory;
}

export type PlaintextMetadataAllowlist = Readonly<
  Record<string, Readonly<Record<string, PlaintextMetadataAllowlistEntry>>>
>;

/** Machine-readable registry (ADR-0070); column additions require an explicit registry diff in the same PR. */
export const PLAINTEXT_METADATA_ALLOWLIST = {
  ...PLAINTEXT_METADATA_ALLOWLIST_APP_CONNECTIONS,
  ...PLAINTEXT_METADATA_ALLOWLIST_AGENT_SESSIONS,
  ...PLAINTEXT_METADATA_ALLOWLIST_PROTECTED_CHANGES,
  ...PLAINTEXT_METADATA_ALLOWLIST_APPROVALS,
  audit_events: {
    actor_machine_identity_id: { category: "actor-id" },
    actor_type: { category: "type-code" },
    actor_user_id: { category: "actor-id" },
    created_at: { category: "timestamp" },
    details: { category: "validated-payload" },
    environment_id: { category: "opaque-id" },
    event_code: { category: "type-code" },
    id: { category: "opaque-id" },
    operation_id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    outcome: { category: "status-code" },
    project_id: { category: "opaque-id" },
    related_resource_id: { category: "opaque-id" },
    related_resource_type: { category: "type-code" },
    request_id: { category: "opaque-id" },
    resource_id: { category: "opaque-id" },
    resource_type: { category: "type-code" },
    result_code: { category: "type-code" },
  },
  first_value_feedback: {
    actor_user_id: { category: "actor-id" },
    created_at: { category: "timestamp" },
    feedback_kind: { category: "type-code" },
    grant_id: { category: "opaque-id" },
    id: { category: "opaque-id" },
    note: { category: "type-code" },
    operation_id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    request_id: { category: "opaque-id" },
  },
  environments: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    is_protected: { category: "flag" },
    lifecycle_stage: { category: "type-code" },
    org_id: { category: "opaque-id" },
    preview_non_production_confirmed_at: { category: "timestamp" },
    preview_non_production_confirmed_by_user_id: { category: "actor-id" },
    project_id: { category: "opaque-id" },
  },
  instances: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
  },
  invitations: {
    accepted_at: { category: "timestamp" },
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    invitee_user_id: { category: "actor-id" },
    membership_id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    role_preset: { category: "type-code" },
    status: { category: "status-code" },
    team_id: { category: "opaque-id" },
  },
  machine_identities: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    status: { category: "status-code" },
  },
  machine_identity_memberships: {
    authorization_scopes: { category: "type-code" },
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    machine_identity_id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
  },
  machine_identity_github_actions_oidc: {
    created_at: { category: "timestamp" },
    credential_scopes: { category: "type-code" },
    environment_id: { category: "opaque-id" },
    github_environment: { category: "type-code" },
    github_repository: { category: "type-code" },
    github_repository_id: { category: "opaque-id" },
    github_repository_owner_id: { category: "opaque-id" },
    id: { category: "opaque-id" },
    machine_identity_id: { category: "opaque-id" },
    oidc_audience: { category: "type-code" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    status: { category: "status-code" },
  },
  machine_identity_environment_deploy_keys: {
    created_at: { category: "timestamp" },
    credential_scopes: { category: "type-code" },
    environment_id: { category: "opaque-id" },
    expires_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    machine_identity_id: { category: "opaque-id" },
    non_expiring: { category: "status-code" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    rotation_interval_seconds: { category: "type-code" },
    rotation_reminder_interval_seconds: { category: "type-code" },
    runtime_policy_key_ids: { category: "opaque-id" },
    secret_hash_algorithm: { category: "type-code" },
    secret_hash_b64: { category: "ciphertext-ref" },
    secret_hash_salt_b64: { category: "ciphertext-ref" },
    status: { category: "status-code" },
  },
  memberships: {
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    role_preset: { category: "type-code" },
    team_id: { category: "opaque-id" },
    user_id: { category: "actor-id" },
  },
  operations: {
    created_at: { category: "timestamp" },
    execution_deadline: { category: "timestamp" },
    id: { category: "opaque-id" },
    idempotency_key: { category: "opaque-id" },
    intent_code: { category: "type-code" },
    org_id: { category: "opaque-id" },
    progress: { category: "validated-payload" },
    state: { category: "status-code" },
    updated_at: { category: "timestamp" },
  },
  organization_data_keys: {
    created_at: { category: "timestamp" },
    custody_evidence_ref: { category: "opaque-id" },
    id: { category: "opaque-id" },
    key_version: { category: "key-version" },
    org_id: { category: "opaque-id" },
    root_key_version: { category: "key-version" },
    status: { category: "status-code" },
    updated_at: { category: "timestamp" },
    wrapped_storage_ref: { category: "ciphertext-ref" },
  },
  organizations: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    instance_id: { category: "opaque-id" },
  },
  project_data_keys: {
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    key_version: { category: "key-version" },
    org_id: { category: "opaque-id" },
    organization_data_key_version: { category: "key-version" },
    project_id: { category: "opaque-id" },
    status: { category: "status-code" },
    updated_at: { category: "timestamp" },
    wrapped_storage_ref: { category: "ciphertext-ref" },
  },
  projects: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
  },
  provider_credentials: {
    app_connection_id: { category: "opaque-id" },
    ciphertext_storage_ref: { category: "ciphertext-ref" },
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    organization_data_key_version: { category: "key-version" },
    provider: { category: "type-code" },
  },
  ...PLAINTEXT_METADATA_ALLOWLIST_SECRETS,
  ...PLAINTEXT_METADATA_ALLOWLIST_RUNTIME_INJECTION,
  sensitive_metadata_fields: {
    ciphertext_storage_ref: { category: "ciphertext-ref" },
    created_at: { category: "timestamp" },
    field_key: { category: "type-code" },
    metadata_type: { category: "type-code" },
    org_id: { category: "opaque-id" },
    organization_data_key_version: { category: "key-version" },
    project_data_key_version: { category: "key-version" },
    record_resource_id: { category: "opaque-id" },
    scope_project_id: { category: "opaque-id" },
  },
  sync_target_leases: {
    created_at: { category: "timestamp" },
    expires_at: { category: "timestamp" },
    fencing_token: { category: "count" },
    held_by_operation_id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    provider_kind: { category: "type-code" },
    target_identity: { category: "plaintext-lookup-key" },
    updated_at: { category: "timestamp" },
  },
  teams: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    is_default: { category: "flag" },
    org_id: { category: "opaque-id" },
  },
  ...PLAINTEXT_METADATA_ALLOWLIST_INSTANCE_BOOTSTRAP,
  ...PLAINTEXT_METADATA_ALLOWLIST_WEBHOOKS,
} as const satisfies PlaintextMetadataAllowlist;
