/**
 * Plaintext Metadata Allowlist registry (ADR-0070).
 * Every column of every user table must appear here with an explicit category.
 */
export const PLAINTEXT_METADATA_CATEGORIES = [
  "opaque-id",
  "display-name",
  "type-code",
  "status-code",
  "timestamp",
  "actor-id",
  "count",
  "flag",
  "ciphertext-ref",
  "key-version",
] as const;

export type PlaintextMetadataCategory = (typeof PLAINTEXT_METADATA_CATEGORIES)[number];

export interface PlaintextMetadataAllowlistEntry {
  category: PlaintextMetadataCategory;
}

export type PlaintextMetadataAllowlist = Readonly<
  Record<string, Readonly<Record<string, PlaintextMetadataAllowlistEntry>>>
>;

/**
 * Machine-readable registry checked in beside the Drizzle schema source of truth.
 * Adding a column requires an explicit registry diff in the same PR.
 */
export const PLAINTEXT_METADATA_ALLOWLIST = {
  app_connections: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    provider: { category: "type-code" },
  },
  audit_events: {
    actor_type: { category: "type-code" },
    actor_user_id: { category: "actor-id" },
    created_at: { category: "timestamp" },
    details: { category: "type-code" },
    environment_id: { category: "opaque-id" },
    event_code: { category: "type-code" },
    id: { category: "opaque-id" },
    operation_id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    outcome: { category: "status-code" },
    project_id: { category: "opaque-id" },
    related_resource_id: { category: "opaque-id" },
    related_resource_type: { category: "type-code" },
    request_id: { category: "opaque-id" },
    resource_id: { category: "opaque-id" },
    resource_type: { category: "type-code" },
    result_code: { category: "type-code" },
  },
  bootstrap_operator_claims: {
    consumed_at: { category: "timestamp" },
    consumed_by_user_id: { category: "actor-id" },
    created_at: { category: "timestamp" },
    first_organization_id: { category: "opaque-id" },
    id: { category: "opaque-id" },
    instance_id: { category: "opaque-id" },
    status: { category: "status-code" },
  },
  bootstrap_secret_verifiers: {
    algorithm: { category: "type-code" },
    consumed_at: { category: "timestamp" },
    created_at: { category: "timestamp" },
    hash_b64: { category: "ciphertext-ref" },
    instance_id: { category: "opaque-id" },
    salt_b64: { category: "ciphertext-ref" },
    secret_version: { category: "count" },
  },
  environments: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    is_protected: { category: "flag" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
  },
  injection_grants: {
    consumed_at: { category: "timestamp" },
    created_at: { category: "timestamp" },
    environment_id: { category: "opaque-id" },
    expires_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    secret_ids: { category: "opaque-id" },
    secret_version_id: { category: "opaque-id" },
    variable_keys: { category: "type-code" },
  },
  instance_configurations: {
    created_at: { category: "timestamp" },
    instance_id: { category: "opaque-id" },
    public_onboarding_enabled: { category: "flag" },
    signup_lockdown_enabled: { category: "flag" },
    updated_at: { category: "timestamp" },
  },
  instance_identity_configurations: {
    created_at: { category: "timestamp" },
    human_identity_provider: { category: "type-code" },
    instance_id: { category: "opaque-id" },
    workos_client_id: { category: "opaque-id" },
  },
  instance_operators: {
    created_at: { category: "timestamp" },
    grant_origin: { category: "type-code" },
    id: { category: "opaque-id" },
    instance_id: { category: "opaque-id" },
    user_id: { category: "actor-id" },
  },
  instances: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
  },
  invitations: {
    accepted_at: { category: "timestamp" },
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    invitee_user_id: { category: "actor-id" },
    membership_id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    role_preset: { category: "type-code" },
    status: { category: "status-code" },
    team_id: { category: "opaque-id" },
  },
  machine_identities: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    status: { category: "status-code" },
  },
  machine_identity_memberships: {
    authorization_scopes: { category: "type-code" },
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    machine_identity_id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
  },
  memberships: {
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    role_preset: { category: "type-code" },
    team_id: { category: "opaque-id" },
    user_id: { category: "actor-id" },
  },
  operations: {
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    idempotency_key: { category: "opaque-id" },
    intent_code: { category: "type-code" },
    org_id: { category: "opaque-id" },
    progress: { category: "type-code" },
    state: { category: "status-code" },
    updated_at: { category: "timestamp" },
  },
  organization_data_keys: {
    created_at: { category: "timestamp" },
    custody_evidence_ref: { category: "opaque-id" },
    id: { category: "opaque-id" },
    key_version: { category: "key-version" },
    org_id: { category: "opaque-id" },
    root_key_version: { category: "key-version" },
    status: { category: "status-code" },
    updated_at: { category: "timestamp" },
    wrapped_storage_ref: { category: "ciphertext-ref" },
  },
  organizations: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    instance_id: { category: "opaque-id" },
  },
  project_data_keys: {
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    key_version: { category: "key-version" },
    org_id: { category: "opaque-id" },
    organization_data_key_version: { category: "key-version" },
    project_id: { category: "opaque-id" },
    status: { category: "status-code" },
    updated_at: { category: "timestamp" },
    wrapped_storage_ref: { category: "ciphertext-ref" },
  },
  projects: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
  },
  provider_credentials: {
    app_connection_id: { category: "opaque-id" },
    ciphertext_storage_ref: { category: "ciphertext-ref" },
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    organization_data_key_version: { category: "key-version" },
    provider: { category: "type-code" },
  },
  secret_versions: {
    ciphertext_storage_ref: { category: "ciphertext-ref" },
    created_at: { category: "timestamp" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    organization_data_key_version: { category: "key-version" },
    project_data_key_version: { category: "key-version" },
    secret_id: { category: "opaque-id" },
    version_number: { category: "count" },
  },
  secrets: {
    created_at: { category: "timestamp" },
    current_version_id: { category: "opaque-id" },
    environment_id: { category: "opaque-id" },
    id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    variable_key: { category: "type-code" },
  },
  sensitive_metadata_fields: {
    ciphertext_storage_ref: { category: "ciphertext-ref" },
    created_at: { category: "timestamp" },
    field_key: { category: "type-code" },
    metadata_type: { category: "type-code" },
    org_id: { category: "opaque-id" },
    organization_data_key_version: { category: "key-version" },
    project_data_key_version: { category: "key-version" },
    record_resource_id: { category: "opaque-id" },
    scope_project_id: { category: "opaque-id" },
  },
  sync_target_leases: {
    created_at: { category: "timestamp" },
    expires_at: { category: "timestamp" },
    fencing_token: { category: "count" },
    held_by_operation_id: { category: "opaque-id" },
    org_id: { category: "opaque-id" },
    project_id: { category: "opaque-id" },
    provider_kind: { category: "type-code" },
    target_identity: { category: "opaque-id" },
    updated_at: { category: "timestamp" },
  },
  teams: {
    created_at: { category: "timestamp" },
    display_name: { category: "display-name" },
    id: { category: "opaque-id" },
    is_default: { category: "flag" },
    org_id: { category: "opaque-id" },
  },
} as const satisfies PlaintextMetadataAllowlist;
