import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const envPath = join(root, ".env.local");
const envFile = ".env.local";

const localDefaults = [
  ["INSECUR_POSTGRES_PORT", () => "54321"],
  ["INSECUR_POSTGRES_DB", () => "insecur_dev"],
  ["INSECUR_POSTGRES_SUPERUSER", () => "insecur_postgres"],
  ["INSECUR_POSTGRES_SUPERUSER_PASSWORD", createSecret],
  ["INSECUR_POSTGRES_MIGRATION_ROLE", () => "insecur_migration"],
  ["INSECUR_POSTGRES_MIGRATION_PASSWORD", createSecret],
  ["INSECUR_POSTGRES_RUNTIME_ROLE", () => "insecur_runtime"],
  ["INSECUR_POSTGRES_RUNTIME_PASSWORD", createSecret],
  ["DATABASE_URL_MIGRATION", createMigrationUrl],
  ["DATABASE_URL_RUNTIME", createRuntimeUrl],
];

const actions = new Map([
  ["env", writeEnv],
  ["up", up],
  ["down", down],
  ["reset", reset],
  ["guard", guard],
  ["help", help],
]);

const action = process.argv[2] ?? "help";
const run = actions.get(action);

if (!run) {
  help();
  process.exitCode = 1;
} else {
  run();
}

function writeEnv() {
  const existing = readEnv();
  const resolved = resolveEnv(existing);
  const missing = Array.from(resolved).filter(([key]) => isUnset(existing.get(key)));
  appendMissing(missing);
  console.log(`OK .env.local has local Postgres keys (${missing.length} added)`);
}

function up() {
  writeEnv();
  compose(["up", "--wait", "postgres"]);
}

function down() {
  writeEnv();
  compose(["down"]);
}

function reset() {
  writeEnv();
  compose(["down", "--volumes", "--remove-orphans"]);
  compose(["up", "--wait", "postgres"]);
  compose(["exec", "-T", "postgres", "sh", "/usr/local/bin/insecur-postgres-guard"]);
}

function guard() {
  writeEnv();
  compose(["up", "--wait", "postgres"]);
  compose(["exec", "-T", "postgres", "sh", "/usr/local/bin/insecur-postgres-guard"]);
}

function help() {
  console.log("Usage: pnpm dev:db:{env|up|down|reset|guard}");
}

function compose(args) {
  const result = spawnSync("docker", ["compose", "--env-file", envFile, ...args], {
    cwd: root,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function readEnv() {
  if (!existsSync(envPath)) {
    return new Map();
  }

  const entries = readFileSync(envPath, "utf8").matchAll(/^([A-Z0-9_]+)=(.*)$/gmu);
  return new Map(Array.from(entries, (match) => [match[1], match[2]]));
}

function resolveEnv(existing) {
  const resolved = new Map(existing);

  for (const [key, value] of localDefaults) {
    if (isUnset(resolved.get(key))) {
      resolved.set(key, value(resolved));
    }
  }

  return resolved;
}

function appendMissing(missing) {
  if (missing.length === 0) {
    return;
  }

  const lines = ["", "# Local Postgres scaffold generated by pnpm dev:db:env"];
  appendFileSync(envPath, `${lines.concat(formatEnv(missing)).join("\n")}\n`);
}

function formatEnv(entries) {
  return entries.map(([key, value]) => `${key}=${value}`);
}

function isUnset(value) {
  return value === undefined || value === "";
}

function createSecret() {
  return randomBytes(24).toString("hex");
}

function createMigrationUrl(values) {
  return createUrl(
    values,
    "INSECUR_POSTGRES_MIGRATION_ROLE",
    "INSECUR_POSTGRES_MIGRATION_PASSWORD",
  );
}

function createRuntimeUrl(values) {
  return createUrl(values, "INSECUR_POSTGRES_RUNTIME_ROLE", "INSECUR_POSTGRES_RUNTIME_PASSWORD");
}

function createUrl(values, roleKey, passwordKey) {
  const role = encodeURIComponent(values.get(roleKey));
  const password = encodeURIComponent(values.get(passwordKey));
  const port = encodeURIComponent(values.get("INSECUR_POSTGRES_PORT"));
  const database = encodeURIComponent(values.get("INSECUR_POSTGRES_DB"));
  return `postgres://${role}:${password}@127.0.0.1:${port}/${database}`;
}
