import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const envPath = join(root, ".env.local");
const envFile = ".env.local";

const localDefaults = [
  ["INSECUR_POSTGRES_PORT", () => "54321"],
  ["INSECUR_POSTGRES_DB", () => "insecur_dev"],
  ["INSECUR_POSTGRES_SUPERUSER", () => "insecur_postgres"],
  ["INSECUR_POSTGRES_SUPERUSER_PASSWORD", createSecret],
  ["INSECUR_POSTGRES_MIGRATION_ROLE", () => "insecur_migration"],
  ["INSECUR_POSTGRES_MIGRATION_PASSWORD", createSecret],
  ["INSECUR_POSTGRES_RUNTIME_ROLE", () => "insecur_runtime"],
  ["INSECUR_POSTGRES_RUNTIME_PASSWORD", createSecret],
  ["DATABASE_URL_MIGRATION", createMigrationUrl],
  ["DATABASE_URL_RUNTIME", createRuntimeUrl],
];

const actions = new Map([
  ["env", writeEnv],
  ["up", up],
  ["down", down],
  ["reset", reset],
  ["reset-service", resetService],
  ["guard", guard],
  ["help", help],
]);

const action = process.argv[2] ?? "help";
const run = actions.get(action);

if (!run) {
  help();
  process.exitCode = 1;
} else {
  run();
}

function writeEnv() {
  const existing = readEnv();
  const resolved = resolveEnv(existing);
  const missing = Array.from(resolved).filter(([key]) => isUnset(existing.get(key)));
  appendMissing(missing);
  console.log(`OK .env.local has local Postgres keys (${missing.length} added)`);
}

function up() {
  writeEnv();
  compose(["up", "--wait", "postgres"]);
}

function down() {
  writeEnv();
  compose(["down"]);
}

function reset() {
  writeEnv();
  compose(["down", "--volumes", "--remove-orphans"]);
  compose(["up", "--wait", "postgres"]);
  compose(["exec", "-T", "postgres", "sh", "/usr/local/bin/insecur-postgres-guard"]);
  migrateLocal();
}

function resetService() {
  writeEnv();
  if (!hasCommand("psql")) {
    console.log("psql not found on PATH; falling back to Docker Compose Postgres reset.");
    reset();
    return;
  }

  const resolved = resolveEnv(readEnv());
  const env = servicePostgresEnv(resolved);

  runPsql(
    [
      "--username",
      resolved.get("INSECUR_POSTGRES_SUPERUSER"),
      "--dbname",
      "postgres",
      "--set=ON_ERROR_STOP=1",
      "--set",
      `db_name=${resolved.get("INSECUR_POSTGRES_DB")}`,
    ],
    `
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = :'db_name' AND pid <> pg_backend_pid();
SELECT format('DROP DATABASE IF EXISTS %I', :'db_name')\\gexec
SELECT format('CREATE DATABASE %I', :'db_name')\\gexec
`,
    env,
  );

  runScript("bash", [join(root, "infra/postgres/init/001-local-roles.sh")], env);
  runScript("sh", [join(root, "infra/postgres/check-runtime-role.sh")], {
    ...env,
    INSECUR_POSTGRES_INTERNAL_PORT: resolved.get("INSECUR_POSTGRES_PORT"),
  });
  migrateLocal();
}

function migrateLocal() {
  writeEnv();
  const resolved = resolveEnv(readEnv());
  const env = { ...process.env };
  for (const [key, value] of resolved) {
    env[key] = value;
  }

  const result = spawnSync("pnpm", ["--filter", "@insecur/tenant-store", "migrate:local"], {
    cwd: root,
    env,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function guard() {
  writeEnv();
  compose(["up", "--wait", "postgres"]);
  compose(["exec", "-T", "postgres", "sh", "/usr/local/bin/insecur-postgres-guard"]);
}

function help() {
  console.log("Usage: pnpm dev:db:{env|up|down|reset|reset-service|guard}");
}

function compose(args) {
  const result = spawnSync("docker", ["compose", "--env-file", envFile, ...args], {
    cwd: root,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function readEnv() {
  if (!existsSync(envPath)) {
    return new Map();
  }

  const entries = readFileSync(envPath, "utf8").matchAll(/^([A-Z0-9_]+)=(.*)$/gmu);
  return new Map(Array.from(entries, (match) => [match[1], match[2]]));
}

function resolveEnv(existing) {
  const resolved = new Map(existing);

  for (const [key, value] of localDefaults) {
    if (isUnset(resolved.get(key))) {
      resolved.set(key, value(resolved));
    }
  }

  return resolved;
}

function appendMissing(missing) {
  if (missing.length === 0) {
    return;
  }

  const lines = ["", "# Local Postgres scaffold generated by pnpm dev:db:env"];
  appendFileSync(envPath, `${lines.concat(formatEnv(missing)).join("\n")}\n`);
}

function formatEnv(entries) {
  return entries.map(([key, value]) => `${key}=${value}`);
}

function isUnset(value) {
  return value === undefined || value === "";
}

function createSecret() {
  return randomBytes(24).toString("hex");
}

function createMigrationUrl(values) {
  return createUrl(
    values,
    "INSECUR_POSTGRES_MIGRATION_ROLE",
    "INSECUR_POSTGRES_MIGRATION_PASSWORD",
  );
}

function createRuntimeUrl(values) {
  return createUrl(values, "INSECUR_POSTGRES_RUNTIME_ROLE", "INSECUR_POSTGRES_RUNTIME_PASSWORD");
}

function createUrl(values, roleKey, passwordKey) {
  const role = encodeURIComponent(values.get(roleKey));
  const password = encodeURIComponent(values.get(passwordKey));
  const port = encodeURIComponent(values.get("INSECUR_POSTGRES_PORT"));
  const database = encodeURIComponent(values.get("INSECUR_POSTGRES_DB"));
  return `postgres://${role}:${password}@127.0.0.1:${port}/${database}`;
}

function servicePostgresEnv(values) {
  return {
    ...process.env,
    PGHOST: "127.0.0.1",
    PGPORT: values.get("INSECUR_POSTGRES_PORT"),
    PGPASSWORD: values.get("INSECUR_POSTGRES_SUPERUSER_PASSWORD"),
    POSTGRES_USER: values.get("INSECUR_POSTGRES_SUPERUSER"),
    POSTGRES_DB: values.get("INSECUR_POSTGRES_DB"),
    INSECUR_POSTGRES_DB: values.get("INSECUR_POSTGRES_DB"),
    INSECUR_POSTGRES_MIGRATION_ROLE: values.get("INSECUR_POSTGRES_MIGRATION_ROLE"),
    INSECUR_POSTGRES_MIGRATION_PASSWORD: values.get("INSECUR_POSTGRES_MIGRATION_PASSWORD"),
    INSECUR_POSTGRES_RUNTIME_ROLE: values.get("INSECUR_POSTGRES_RUNTIME_ROLE"),
    INSECUR_POSTGRES_RUNTIME_PASSWORD: values.get("INSECUR_POSTGRES_RUNTIME_PASSWORD"),
  };
}

function runPsql(args, input, env) {
  const result = spawnSync("psql", args, {
    cwd: root,
    env,
    input,
    stdio: ["pipe", "inherit", "inherit"],
  });

  if (result.error) {
    console.error(`psql failed to start: ${result.error.message}`);
    process.exit(1);
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function runScript(command, args, env) {
  const result = spawnSync(command, args, {
    cwd: root,
    env,
    stdio: "inherit",
  });

  if (result.error) {
    console.error(`${command} failed to start: ${result.error.message}`);
    process.exit(1);
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function hasCommand(command) {
  const result = spawnSync(command, ["--version"], {
    stdio: "ignore",
  });
  return !result.error && result.status === 0;
}
